### ISSUE TITLE
Keeping track of changes made for Milestone 4

### ISSUE THREAD

**Issue by erictsai1208** [UBC-MDS/boardgame_rating_predictor#37]
Hey guys, since we have to comment on the [peer review page](https://github.com/UBC-MDS/data-analysis-review-2022/issues/21) at least 5 comments we agreed with and our implementation, I figured we can keep track of them here and them just paste it all into the peer review page once we have all 5 implementations finished.

**Comment by erictsai1208** [comment]
"In a similar scope, I noticed that plot_top_10_mechanics() and plot_top_10_categories() are pretty similar with only a few settings changed, so you could use a helper here for both grouped bar charts and set some parameters to change depending on whether you're plotting the mechanics or categories."
[PR link](https://github.com/UBC-MDS/boardgame_rating_predictor/pull/32/files)

**Comment by marianagyby** [comment]
Addressing peer review comment by Lauren: "Along with the Ridge and RandomForestRegressor models, it would be cool to see if your performance improves with the new regularization techniques we have covered in 573 (adding lasso or elastic net regression!) Similarly, since you chose as your scoring metric, perhaps MAPE or RMSE could be a nice option to show alongside that is interpretable relative to your target, user rating."

Will show MAPE scores in addition to R^2 scores and comment on them in the report so they are more interpretable.
- [PR link](https://github.com/UBC-MDS/boardgame_rating_predictor/pull/34)
- [Commit link](https://github.com/UBC-MDS/boardgame_rating_predictor/commit/4456d2d3954ba6b70fbf03778d918778e0d0195b)

Addressing peer review comment by Suraporn: "I can not render boardgame_rating_predictor_report.html. It seems like some codes there are wrong. I would like the author to recheck the report and make it possible to render in Github repository. It will be good if this html report can render properly, so the reader can read the summary report in this file rather than raw file format like boardgame_rating_predictor_report.Rmd."

Will add output of github_document and pdf_document so report can appear rendered on GitHub
- [PR link](https://github.com/UBC-MDS/boardgame_rating_predictor/pull/34)
- [Commit link for .md](https://github.com/UBC-MDS/boardgame_rating_predictor/commit/d9c98bbf4fd4678bd5e143f9425781aafe9ed40d)
- [Commit link for .pdf](https://github.com/UBC-MDS/boardgame_rating_predictor/commit/22e8e9ab0a1bb10ce9d7adfa9b53b630c1393353)

Addressing peer review comment by Natalie: "The code to create the environment produced an error (missing an argument to specify creation of an env from a file)."

Will fix typo in read me environment command.
- [Commit link](https://github.com/UBC-MDS/boardgame_rating_predictor/commit/87e935d7c5dd57ffcd75dd16ea668a5ae7c31fab)

Addressing peer review comment by Suraporn: "The line conda env -f envboard.yaml and 'conda activate envboard' together in Usage section of readme file make it difficult to copy, paste, and run it right away in command line. The author better put it in separated lines, so it is easy to copy and run in terminal command."

Will edit Usage section so commands are easier to copy/paste.
- [commit link](https://github.com/UBC-MDS/boardgame_rating_predictor/commit/c37c79e36d8e6ac52ab8c4572ed1aee13f396ffe)

**Comment by erictsai1208** [comment]
There are a few scripts that can be further improved (e.g. in eda_boardgame.py maybe use a instead, and in prediction_model.py maybe split the main() function into more parts for better readability.
Vikram's commit: [commit link ](https://github.com/UBC-MDS/boardgame_rating_predictor/pull/36/commits/1c4fc50cab6513a43baf7844aa9157351935330e)
